### ISSUE TITLE
Plugin does not show up in Plugin-Manager

### ISSUE THREAD

**Issue by 1Maxnet1** [sgonschorowski/intellij-openjml#1]
When I try to search the Plugin-Manager for this plugin, it cannot find any result.

IntelliJ IDEA 2020.3.1 (Ultimate Edition)

I guess it's due to incompatibility with the current version. Would it be possible to update this plugin to be compatible with the current version ?

**Comment by nour95** [comment]
Yes, please

**Comment by sgonschorowski** [comment]
Hi there,
unfortunately at the moment there are no plans to update the plugin.
Please use an old version of IntelliJ or update the plugin by yourselves.

Best regards

**Comment by 1Maxnet1** [comment]
Okay understandable. Could you archive the repo to make clear it does not gets developed any more?
